<?php

if( function_exists('acf_add_options_page') ) {
	acf_add_options_page(array(
		'page_title' 	=> __( 'Event options', 'ventcamp' ),
		'menu_title'	=> __( 'Event', 'ventcamp' ),
		'menu_slug' 	=> 'vncp-event-options',
		'capability'	=> 'edit_posts',
		'redirect'		=> false,
		'position'		=> '45.5'
	));
}

/* Event ACF */
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_event_options',
	'title' => __( 'Event options', 'ventcamp' ),
	'fields' => array (
		array (
			'key' => 'field_event_type',
			'label' => __( 'Event type', 'ventcamp' ),
			'name' => 'vncp_event_type',
			'type' => 'radio',
			'instructions' => __( 'Choose your event type', 'ventcamp' ),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'one_day_no_threads' => __( 'Single day schedule', 'ventcamp' ),
				// 'one_day_with_threads' => 'One day with threads',
				'multi_day_no_threads' => __( 'Multi days schedule', 'ventcamp' ),
				'multi_day_with_threads' => __( 'Multi days & venues schedule', 'ventcamp' ),
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
		array (
		  'key' => 'field_single_day',
		  'label' => __( 'Single day schedule', 'ventcamp' ),
		  'name' => 'vncp_one_day_schedule',
		  'type' => 'repeater',
		  'instructions' => '',
		  'required' => 1,
		  'conditional_logic' => array (
		    array (
		      array (
		        'field' => 'field_event_type',
		        'operator' => '==',
		        'value' => 'one_day_no_threads',
		      ),
		    ),
		  ),
		  'wrapper' => array (
		    'width' => '',
		    'class' => 'acf-single-repeater',
		    'id' => '',
		  ),
		  'collapsed' => 'field_5654af8c48901',
		  'min' => '',
		  'max' => '1',
		  'layout' => 'block',
		  'button_label' => __( 'Add a day', 'ventcamp' ),
		  'sub_fields' => array (
		    array (
		      'key' => 'field_single_day_date',
		      'label' => __( 'Date', 'ventcamp' ),
		      'name' => 'date',
		      'type' => 'text',
		      'instructions' => '',
		      'required' => 0,
		      'conditional_logic' => 0,
		      'wrapper' => array (
		        'width' => '',
		        'class' => '',
		        'id' => '',
		      ),
		      'default_value' => '',
		      'placeholder' => '',
		      'prepend' => '',
		      'append' => '',
		      'maxlength' => '',
		      'readonly' => 0,
		      'disabled' => 0,
		    ),
		    array (
		      'key' => 'field_single_day_lectures',
		      'label' => __( 'Thread schedule', 'ventcamp' ),
		      'name' => 'lectures',
		      'type' => 'repeater',
		      'instructions' => '',
		      'required' => 0,
		      'conditional_logic' => 0,
		      'wrapper' => array (
		        'width' => '',
		        'class' => '',
		        'id' => '',
		      ),
		      'collapsed' => 'field_single_day_lecture_title',
		      'min' => '',
		      'max' => '',
		      'layout' => 'block',
		      'button_label' => __( 'Add', 'ventcamp' ),
		      'sub_fields' => array (
		        array (
		          'key' => 'field_single_day_lecture_title',
		          'label' => __( 'Title', 'ventcamp' ),
		          'name' => 'title',
		          'type' => 'text',
		          'instructions' => __( 'Lecture title', 'ventcamp' ),
		          'required' => 1,
		          'conditional_logic' => 0,
		          'wrapper' => array (
		            'width' => '',
		            'class' => '',
		            'id' => '',
		          ),
		          'default_value' => '',
		          'placeholder' => '',
		          'prepend' => '',
		          'append' => '',
		          'maxlength' => '',
		          'readonly' => 0,
		          'disabled' => 0,
		        ),
		        array (
		          'key' => 'field_single_day_lecture_location',
		          'label' => __( 'Location', 'ventcamp' ),
		          'name' => 'location',
		          'type' => 'text',
		          'instructions' => '',
		          'required' => 0,
		          'conditional_logic' => 0,
		          'wrapper' => array (
		            'width' => '',
		            'class' => '',
		            'id' => '',
		          ),
		          'default_value' => '',
		          'placeholder' => '',
		          'prepend' => '',
		          'append' => '',
		          'maxlength' => '',
		          'readonly' => 0,
		          'disabled' => 0,
		        ),
		        array (
		          'key' => 'field_single_day_lecture_time',
		          'label' => __( 'Time', 'ventcamp' ),
		          'name' => 'time',
		          'type' => 'text',
		          'instructions' => '',
		          'required' => 0,
		          'conditional_logic' => 0,
		          'wrapper' => array (
		            'width' => '',
		            'class' => '',
		            'id' => '',
		          ),
		          'default_value' => '',
		          'placeholder' => '',
		          'prepend' => '',
		          'append' => '',
		          'maxlength' => '',
		          'readonly' => 0,
		          'disabled' => 0,
		        ),
		        array (
		          'key' => 'field_single_day_lecture_description',
		          'label' => __( 'Description', 'ventcamp' ),
		          'name' => 'description',
		          'type' => 'textarea',
		          'instructions' => '',
		          'required' => 0,
		          'conditional_logic' => 0,
		          'wrapper' => array (
		            'width' => '',
		            'class' => '',
		            'id' => '',
		          ),
		          'default_value' => '',
		          'placeholder' => '',
		          'maxlength' => '',
		          'rows' => 12,
		          'new_lines' => '',
		          'readonly' => 0,
		          'disabled' => 0,
		        ),
		        array (
		          'key' => 'field_single_day_lecture_info',
		          'label' => __( 'Extra Info', 'ventcamp' ),
		          'name' => 'extra_info',
		          'type' => 'text',
		          'instructions' => '',
		          'required' => 0,
		          'conditional_logic' => 0,
		          'wrapper' => array (
		            'width' => '',
		            'class' => '',
		            'id' => '',
		          ),
		          'default_value' => '',
		          'placeholder' => '',
		          'prepend' => '',
		          'append' => '',
		          'maxlength' => '',
		          'readonly' => 0,
		          'disabled' => 0,
		        ),
		      ),
		    ),
		  ),
		),
		array (
			'key' => 'field_5654b04de8a66',
			'label' => __( 'Schedule with threads/auditoriums', 'ventcamp' ),
			'name' => 'vncp_md_w_thrds',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_event_type',
						'operator' => '==',
						'value' => 'multi_day_with_threads',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5654b04ee8a67',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => __( 'Add a day', 'ventcamp' ),
			'sub_fields' => array (
				array (
					'key' => 'field_5654b04ee8a67',
					'label' => __( 'Title', 'ventcamp' ),
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5654b04ee8a68',
					'label' => __( 'Date', 'ventcamp' ),
					'name' => 'date',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5654b06ae8a6f',
					'label' => __( 'Threads', 'ventcamp' ),
					'name' => 'threads',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5654b08ae8a70',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => __( 'Add thread', 'ventcamp' ),
					'sub_fields' => array (
						array (
							'key' => 'field_5654b08ae8a70',
							'label' => __( 'Thread title', 'ventcamp' ),
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5654b09ce8a71',
							'label' => __( 'Thread Schedule', 'ventcamp' ),
							'name' => 'lectures',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5654b09ce8a72',
							'min' => '',
							'max' => '',
							'layout' => 'block',
							'button_label' => __( 'Add', 'ventcamp' ),
							'sub_fields' => array (
								array (
									'key' => 'field_5654b09ce8a72',
									'label' => __( 'Title', 'ventcamp' ),
									'name' => 'title',
									'type' => 'text',
									'instructions' => __( 'Lecture title', 'ventcamp' ),
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5654b09ce8a73',
									'label' => __( 'Time', 'ventcamp' ),
									'name' => 'time',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5654b09ce8a74',
									'label' => __( 'Description', 'ventcamp' ),
									'name' => 'description',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => 12,
									'new_lines' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5654b09ce8a75',
									'label' => __( 'Lecturer', 'ventcamp' ),
									'name' => 'lecturer',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5654b09ce8a76',
									'label' => __( 'Icon', 'ventcamp' ),
									'name' => 'icon',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => '70x70',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
				),
			),
		),

		array (
			'key' => 'field_5654af68487b7',
			'label' => __( 'Schedule without threads/auditoriums', 'ventcamp' ),
			'name' => 'vncp_md_wo_thrds',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_event_type',
						'operator' => '==',
						'value' => 'multi_day_no_threads',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5654af8c487b8',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => __( 'Add a day', 'ventcamp' ),
			'sub_fields' => array (
				array (
					'key' => 'field_5654af8c487b8',
					'label' => __( 'Title', 'ventcamp' ),
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5654af9a487b9',
					'label' => __( 'Date', 'ventcamp' ),
					'name' => 'date',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5654afb0487ba',
					'label' => __( 'Thread schedule', 'ventcamp' ),
					'name' => 'lectures',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5654afb0487bb',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => __( 'Add', 'ventcamp' ),
					'sub_fields' => array (
						array (
							'key' => 'field_5654afb0487bb',
							'label' => __( 'Title', 'ventcamp' ),
							'name' => 'title',
							'type' => 'text',
							'instructions' => __( 'Lecture title', 'ventcamp' ),
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5654afb0487bc',
							'label' => __( 'Time', 'ventcamp' ),
							'name' => 'time',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5654afb1487bd',
							'label' => __( 'Description', 'ventcamp' ),
							'name' => 'description',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 12,
							'new_lines' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5654afb1487be',
							'label' => __( 'Lecturer', 'ventcamp' ),
							'name' => 'lecturer',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5654afb1487bf',
							'label' => __( 'Icon', 'ventcamp' ),
							'name' => 'icon',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => '70x70',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
			),
		),

	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'vncp-event-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;