<?php 
defined('ABSPATH') or die('No direct access');

if( !function_exists('ventamp_enqueue_icons') ) {
	function ventamp_enqueue_icons(){
		wp_enqueue_style( 'font-lineicons', get_template_directory() . '/assets/css/font-lineicons.css' );
	}
}


if( !function_exists('ventcamp_get_icons_list') ) {
	function ventcamp_get_icons_list(){
	return array('icon-alerts-01',
	'icon-alerts-02',
	'icon-alerts-03',
	'icon-alerts-04',
	'icon-alerts-05',
	'icon-alerts-06',
	'icon-alerts-07',
	'icon-alerts-08',
	'icon-alerts-09',
	'icon-alerts-10',
	'icon-alerts-11',
	'icon-alerts-12',
	'icon-alerts-13',
	'icon-arrows-08',
	'icon-arrows-07',
	'icon-arrows-06',
	'icon-arrows-05',
	'icon-arrows-03',
	'icon-arrows-04',
	'icon-arrows-02',
	'icon-arrows-01',
	'icon-alerts-18',
	'icon-alerts-17',
	'icon-alerts-16',
	'icon-alerts-15',
	'icon-alerts-14',
	'icon-arrows-09',
	'icon-arrows-10',
	'icon-arrows-11',
	'icon-arrows-12',
	'icon-arrows-13',
	'icon-arrows-14',
	'icon-arrows-15',
	'icon-arrows-16',
	'icon-arrows-22',
	'icon-arrows-17',
	'icon-arrows-18',
	'icon-arrows-19',
	'icon-arrows-20',
	'icon-arrows-21',
	'icon-arrows-30',
	'icon-arrows-31',
	'icon-arrows-32',
	'icon-arrows-33',
	'icon-arrows-34',
	'icon-arrows-23',
	'icon-arrows-24',
	'icon-arrows-25',
	'icon-arrows-26',
	'icon-arrows-27',
	'icon-arrows-28',
	'icon-arrows-29',
	'icon-arrows-36',
	'icon-arrows-37',
	'icon-arrows-38',
	'icon-arrows-39',
	'icon-arrows-40',
	'icon-arrows-41',
	'icon-badges-votes-01',
	'icon-badges-votes-02',
	'icon-arrows-30',
	'icon-badges-votes-03',
	'icon-badges-votes-04',
	'icon-badges-votes-05',
	'icon-badges-votes-06',
	'icon-arrows-35',
	'icon-badges-votes-07',
	'icon-badges-votes-08',
	'icon-badges-votes-09',
	'icon-badges-votes-10',
	'icon-badges-votes-11',
	'icon-badges-votes-12',
	'icon-badges-votes-13',
	'icon-badges-votes-14',
	'icon-badges-votes-15',
	'icon-badges-votes-16',
	'icon-chat-messages-01',
	'icon-chat-messages-02',
	'icon-chat-messages-03',
	'icon-chat-messages-04',
	'icon-chat-messages-05',
	'icon-chat-messages-06',
	'icon-chat-messages-07',
	'icon-chat-messages-08',
	'icon-chat-messages-09',
	'icon-chat-messages-10',
	'icon-chat-messages-11',
	'icon-chat-messages-12',
	'icon-chat-messages-13',
	'icon-chat-messages-14',
	'icon-chat-messages-15',
	'icon-chat-messages-16',
	'icon-documents-bookmarks-01',
	'icon-documents-bookmarks-02',
	'icon-documents-bookmarks-03',
	'icon-documents-bookmarks-04',
	'icon-documents-bookmarks-05',
	'icon-documents-bookmarks-06',
	'icon-documents-bookmarks-07',
	'icon-documents-bookmarks-08',
	'icon-documents-bookmarks-09',
	'icon-documents-bookmarks-10',
	'icon-documents-bookmarks-11',
	'icon-documents-bookmarks-12',
	'icon-documents-bookmarks-13',
	'icon-documents-bookmarks-14',
	'icon-documents-bookmarks-15',
	'icon-documents-bookmarks-16',
	'icon-ecology-01',
	'icon-ecology-02',
	'icon-ecology-03',
	'icon-ecology-04',
	'icon-ecology-05',
	'icon-ecology-06',
	'icon-ecology-07',
	'icon-ecology-08',
	'icon-ecology-09',
	'icon-ecology-10',
	'icon-ecology-11',
	'icon-ecology-12',
	'icon-ecology-13',
	'icon-ecology-14',
	'icon-ecology-15',
	'icon-ecology-16',
	'icon-education-science-01',
	'icon-education-science-02',
	'icon-education-science-03',
	'icon-education-science-04',
	'icon-education-science-05',
	'icon-education-science-06',
	'icon-education-science-07',
	'icon-education-science-08',
	'icon-education-science-09',
	'icon-education-science-10',
	'icon-education-science-11',
	'icon-education-science-12',
	'icon-education-science-13',
	'icon-education-science-14',
	'icon-education-science-15',
	'icon-education-science-16',
	'icon-education-science-17',
	'icon-education-science-18',
	'icon-education-science-19',
	'icon-education-science-20',
	'icon-emoticons-01',
	'icon-emoticons-02',
	'icon-emoticons-03',
	'icon-emoticons-04',
	'icon-emoticons-05',
	'icon-emoticons-06',
	'icon-emoticons-07',
	'icon-emoticons-08',
	'icon-emoticons-09',
	'icon-emoticons-10',
	'icon-emoticons-11',
	'icon-emoticons-12',
	'icon-emoticons-13',
	'icon-emoticons-14',
	'icon-emoticons-15',
	'icon-emoticons-16',
	'icon-emoticons-17',
	'icon-emoticons-18',
	'icon-emoticons-19',
	'icon-emoticons-20',
	'icon-emoticons-21',
	'icon-emoticons-22',
	'icon-emoticons-23',
	'icon-emoticons-24',
	'icon-emoticons-25',
	'icon-emoticons-26',
	'icon-emoticons-27',
	'icon-emoticons-28',
	'icon-emoticons-29',
	'icon-emoticons-30',
	'icon-emoticons-31',
	'icon-emoticons-32',
	'icon-emoticons-33',
	'icon-emoticons-34',
	'icon-emoticons-35',
	'icon-emoticons-artboard-80',
	'icon-faces-users-01',
	'icon-faces-users-02',
	'icon-faces-users-03',
	'icon-faces-users-04',
	'icon-faces-users-05',
	'icon-faces-users-06',
	'icon-faces-users-07',
	'icon-filetypes-01',
	'icon-filetypes-02',
	'icon-filetypes-03',
	'icon-filetypes-04',
	'icon-filetypes-05',
	'icon-filetypes-06',
	'icon-filetypes-07',
	'icon-filetypes-08',
	'icon-filetypes-09',
	'icon-filetypes-10',
	'icon-filetypes-11',
	'icon-filetypes-12',
	'icon-filetypes-13',
	'icon-filetypes-14',
	'icon-filetypes-15',
	'icon-filetypes-16',
	'icon-filetypes-17',
	'icon-food-01',
	'icon-food-02',
	'icon-food-03',
	'icon-food-04',
	'icon-food-05',
	'icon-food-06',
	'icon-food-07',
	'icon-food-08',
	'icon-food-09',
	'icon-food-10',
	'icon-food-11',
	'icon-food-12',
	'icon-food-13',
	'icon-food-14',
	'icon-food-15',
	'icon-food-16',
	'icon-food-17',
	'icon-food-18',
	'icon-graphic-design-01',
	'icon-graphic-design-02',
	'icon-graphic-design-03',
	'icon-graphic-design-04',
	'icon-graphic-design-05',
	'icon-graphic-design-06',
	'icon-graphic-design-07',
	'icon-graphic-design-08',
	'icon-graphic-design-09',
	'icon-graphic-design-10',
	'icon-graphic-design-11',
	'icon-graphic-design-12',
	'icon-graphic-design-13',
	'icon-graphic-design-14',
	'icon-graphic-design-15',
	'icon-graphic-design-16',
	'icon-graphic-design-17',
	'icon-graphic-design-18',
	'icon-graphic-design-19',
	'icon-graphic-design-20',
	'icon-graphic-design-21',
	'icon-graphic-design-22',
	'icon-graphic-design-23',
	'icon-graphic-design-24',
	'icon-graphic-design-25',
	'icon-graphic-design-26',
	'icon-graphic-design-27',
	'icon-graphic-design-28',
	'icon-graphic-design-29',
	'icon-graphic-design-30',
	'icon-graphic-design-31',
	'icon-graphic-design-32',
	'icon-graphic-design-33',
	'icon-graphic-design-34',
	'icon-medical-01',
	'icon-medical-02',
	'icon-medical-03',
	'icon-medical-04',
	'icon-medical-05',
	'icon-medical-06',
	'icon-medical-07',
	'icon-medical-08',
	'icon-medical-09',
	'icon-medical-10',
	'icon-medical-11',
	'icon-medical-12',
	'icon-medical-13',
	'icon-medical-14',
	'icon-medical-15',
	'icon-medical-16',
	'icon-medical-17',
	'icon-medical-18',
	'icon-medical-19',
	'icon-medical-20',
	'icon-medical-21',
	'icon-medical-22',
	'icon-medical-23',
	'icon-medical-24',
	'icon-medical-25',
	'icon-medical-26',
	'icon-medical-27',
	'icon-medical-28',
	'icon-multimedia-01',
	'icon-multimedia-02',
	'icon-multimedia-03',
	'icon-multimedia-04',
	'icon-multimedia-05',
	'icon-multimedia-06',
	'icon-multimedia-07',
	'icon-multimedia-08',
	'icon-multimedia-09',
	'icon-multimedia-10',
	'icon-multimedia-11',
	'icon-multimedia-12',
	'icon-multimedia-13',
	'icon-multimedia-14',
	'icon-multimedia-15',
	'icon-multimedia-16',
	'icon-multimedia-17',
	'icon-multimedia-18',
	'icon-multimedia-19',
	'icon-multimedia-20',
	'icon-multimedia-21',
	'icon-multimedia-22',
	'icon-multimedia-23',
	'icon-multimedia-24',
	'icon-multimedia-25',
	'icon-multimedia-26',
	'icon-multimedia-27',
	'icon-multimedia-28',
	'icon-multimedia-29',
	'icon-multimedia-30',
	'icon-multimedia-31',
	'icon-multimedia-32',
	'icon-multimedia-33',
	'icon-multimedia-34',
	'icon-multimedia-35',
	'icon-multimedia-36',
	'icon-multimedia-37',
	'icon-multimedia-38',
	'icon-multimedia-39',
	'icon-multimedia-40',
	'icon-nature-01',
	'icon-nature-02',
	'icon-nature-03',
	'icon-nature-04',
	'icon-nature-05',
	'icon-nature-06',
	'icon-nature-07',
	'icon-nature-08',
	'icon-nature-09',
	'icon-nature-10',
	'icon-nature-11',
	'icon-nature-12',
	'icon-nature-13',
	'icon-nature-14',
	'icon-office-01',
	'icon-office-01',
	'icon-shopping-15',
	'icon-shopping-16',
	'icon-shopping-17',
	'icon-shopping-18',
	'icon-shopping-19',
	'icon-shopping-20',
	'icon-shopping-21',
	'icon-shopping-22',
	'icon-shopping-23',
	'icon-shopping-24',
	'icon-shopping-25',
	'icon-shopping-26',
	'icon-shopping-27',
	'icon-socialmedia-01',
	'icon-socialmedia-02',
	'icon-socialmedia-03',
	'icon-socialmedia-04',
	'icon-socialmedia-05',
	'icon-socialmedia-06',
	'icon-socialmedia-07',
	'icon-socialmedia-08',
	'icon-socialmedia-09',
	'icon-socialmedia-10',
	'icon-socialmedia-11',
	'icon-socialmedia-12',
	'icon-socialmedia-13',
	'icon-socialmedia-14',
	'icon-socialmedia-15',
	'icon-socialmedia-16',
	'icon-socialmedia-17',
	'icon-socialmedia-18',
	'icon-socialmedia-19',
	'icon-socialmedia-20',
	'icon-socialmedia-21',
	'icon-socialmedia-22',
	'icon-socialmedia-23',
	'icon-socialmedia-24',
	'icon-socialmedia-25',
	'icon-socialmedia-26',
	'icon-socialmedia-27',
	'icon-socialmedia-28',
	'icon-socialmedia-29',
	'icon-sport-01',
	'icon-sport-02',
	'icon-sport-03',
	'icon-sport-04',
	'icon-sport-05',
	'icon-sport-06',
	'icon-sport-07',
	'icon-sport-08',
	'icon-sport-09',
	'icon-sport-10',
	'icon-sport-11',
	'icon-sport-12',
	'icon-sport-13',
	'icon-sport-14',
	'icon-sport-15',
	'icon-sport-16',
	'icon-sport-17',
	'icon-sport-18',
	'icon-text-hierarchy-01',
	'icon-text-hierarchy-02',
	'icon-text-hierarchy-03',
	'icon-text-hierarchy-04',
	'icon-text-hierarchy-05',
	'icon-text-hierarchy-06',
	'icon-text-hierarchy-07',
	'icon-text-hierarchy-08',
	'icon-text-hierarchy-09',
	'icon-text-hierarchy-10',
	'icon-touch-gestures-01',
	'icon-touch-gestures-02',
	'icon-touch-gestures-03',
	'icon-touch-gestures-04',
	'icon-touch-gestures-05',
	'icon-touch-gestures-06',
	'icon-touch-gestures-07',
	'icon-touch-gestures-08',
	'icon-touch-gestures-09',
	'icon-touch-gestures-10',
	'icon-touch-gestures-11',
	'icon-touch-gestures-12',
	'icon-touch-gestures-13',
	'icon-touch-gestures-14',
	'icon-touch-gestures-15',
	'icon-touch-gestures-16',
	'icon-touch-gestures-17',
	'icon-touch-gestures-18',
	'icon-touch-gestures-19',
	'icon-touch-gestures-20',
	'icon-touch-gestures-21',
	'icon-touch-gestures-22',
	'icon-touch-gestures-23',
	'icon-touch-gestures-24',
	'icon-travel-transportation-01',
	'icon-travel-transportation-02',
	'icon-travel-transportation-03',
	'icon-travel-transportation-04',
	'icon-travel-transportation-05',
	'icon-travel-transportation-06',
	'icon-travel-transportation-07',
	'icon-travel-transportation-08',
	'icon-travel-transportation-09',
	'icon-travel-transportation-10',
	'icon-travel-transportation-11',
	'icon-travel-transportation-12',
	'icon-travel-transportation-13',
	'icon-travel-transportation-14',
	'icon-travel-transportation-15',
	'icon-travel-transportation-16',
	'icon-travel-transportation-17',
	'icon-travel-transportation-18',
	'icon-travel-transportation-19',
	'icon-travel-transportation-20',
	'icon-weather-01',
	'icon-weather-02',
	'icon-weather-03',
	'icon-weather-04',
	'icon-weather-05',
	'icon-weather-06',
	'icon-weather-07',
	'icon-weather-08',
	'icon-weather-09',
	'icon-weather-10',
	'icon-weather-11',
	'icon-weather-12',
	'icon-weather-13',
	'icon-weather-14',
	'icon-office-02',
	'icon-office-03',
	'icon-office-04',
	'icon-office-05',
	'icon-office-06',
	'icon-office-07',
	'icon-office-08',
	'icon-office-09',
	'icon-office-10',
	'icon-office-11',
	'icon-office-12',
	'icon-office-13',
	'icon-office-14',
	'icon-office-15',
	'icon-office-16',
	'icon-office-17',
	'icon-office-18',
	'icon-office-19',
	'icon-office-20',
	'icon-office-21',
	'icon-office-22',
	'icon-office-23',
	'icon-office-24',
	'icon-office-25',
	'icon-office-26',
	'icon-office-27',
	'icon-office-28',
	'icon-office-29',
	'icon-office-30',
	'icon-office-31',
	'icon-office-32',
	'icon-office-33',
	'icon-office-34',
	'icon-office-35',
	'icon-office-36',
	'icon-office-37',
	'icon-office-38',
	'icon-office-39',
	'icon-office-40',
	'icon-office-41',
	'icon-office-42',
	'icon-office-43',
	'icon-office-44',
	'icon-office-45',
	'icon-office-46',
	'icon-office-47',
	'icon-office-48',
	'icon-office-49',
	'icon-office-50',
	'icon-office-51',
	'icon-office-52',
	'icon-office-53',
	'icon-office-54',
	'icon-office-55',
	'icon-office-56',
	'icon-office-57',
	'icon-office-58',
	'icon-office-59',
	'icon-office-60',
	'icon-office-61',
	'icon-party-01',
	'icon-party-02',
	'icon-party-03',
	'icon-party-04',
	'icon-party-05',
	'icon-party-06',
	'icon-party-07',
	'icon-party-08',
	'icon-party-09',
	'icon-party-10',
	'icon-party-11',
	'icon-realestate-living-01',
	'icon-realestate-living-02',
	'icon-realestate-living-03',
	'icon-realestate-living-04',
	'icon-realestate-living-05',
	'icon-realestate-living-06',
	'icon-realestate-living-07',
	'icon-realestate-living-08',
	'icon-realestate-living-09',
	'icon-realestate-living-10',
	'icon-realestate-living-11',
	'icon-realestate-living-12',
	'icon-realestate-living-13',
	'icon-realestate-living-14',
	'icon-realestate-living-15',
	'icon-realestate-living-16',
	'icon-seo-icons-01',
	'icon-seo-icons-02',
	'icon-seo-icons-03',
	'icon-seo-icons-04',
	'icon-seo-icons-05',
	'icon-seo-icons-06',
	'icon-seo-icons-07',
	'icon-seo-icons-08',
	'icon-seo-icons-09',
	'icon-seo-icons-10',
	'icon-seo-icons-11',
	'icon-seo-icons-12',
	'icon-seo-icons-13',
	'icon-seo-icons-14',
	'icon-seo-icons-15',
	'icon-seo-icons-16',
	'icon-seo-icons-17',
	'icon-seo-icons-18',
	'icon-seo-icons-19',
	'icon-seo-icons-20',
	'icon-seo-icons-21',
	'icon-seo-icons-22',
	'icon-seo-icons-23',
	'icon-seo-icons-24',
	'icon-seo-icons-25',
	'icon-seo-icons-26',
	'icon-seo-icons-27',
	'icon-seo-icons-28',
	'icon-seo-icons-29',
	'icon-seo-icons-30',
	'icon-seo-icons-31',
	'icon-seo-icons-32',
	'icon-seo-icons-33',
	'icon-seo-icons-34',
	'icon-seo-icons-35',
	'icon-seo-icons-36',
	'icon-seo-icons-37',
	'icon-seo-icons-38',
	'icon-seo-icons-39',
	'icon-seo-icons-40',
	'icon-seo-icons-41',
	'icon-seo-icons-42',
	'icon-shopping-01',
	'icon-shopping-02',
	'icon-shopping-03',
	'icon-shopping-04',
	'icon-shopping-05',
	'icon-shopping-06',
	'icon-shopping-07',
	'icon-shopping-08',
	'icon-shopping-09',
	'icon-shopping-10',
	'icon-shopping-11',
	'icon-shopping-12',
	'icon-shopping-13',
	'icon-shopping-14',
	);
	}
}

if( !function_exists('ventcamp_get_socials') ) {
	function ventcamp_get_socials(){
	return array(
			"500px" => "500px",
			"adn" => "adn",
			"amazon" => "amazon",
			"android" => "android",
			"angellist" => "angellist",
			"apple" => "apple",
			"behance" => "behance",
			"behance-square" => "behance-square",
			"bitbucket" => "bitbucket",
			"bitbucket-square" => "bitbucket-square",
			"bitcoin" => "bitcoin",
			"black-tie" => "black-tie",
			"btc" => "btc",
			"buysellads" => "buysellads",
			"cc-amex" => "cc-amex",
			"cc-diners-club" => "cc-diners-club",
			"cc-discover" => "cc-discover",
			"cc-jcb" => "cc-jcb",
			"cc-mastercard" => "cc-mastercard",
			"cc-paypal" => "cc-paypal",
			"cc-stripe" => "cc-stripe",
			"cc-visa" => "cc-visa",
			"chrome" => "chrome",
			"codepen" => "codepen",
			"connectdevelop" => "connectdevelop",
			"contao" => "contao",
			"css3" => "css3",
			"dashcube" => "dashcube",
			"delicious" => "delicious",
			"deviantart" => "deviantart",
			"digg" => "digg",
			"dribbble" => "dribbble",
			"dropbox" => "dropbox",
			"drupal" => "drupal",
			"empire" => "empire",
			"expeditedssl" => "expeditedssl",
			"facebook" => "facebook",
			"facebook-official" => "facebook-official",
			"facebook-square" => "facebook-square",
			"firefox" => "firefox",
			"flickr" => "flickr",
			"fonticons" => "fonticons",
			"forumbee" => "forumbee",
			"foursquare" => "foursquare",
			"get-pocket" => "get-pocket",
			"gg" => "gg",
			"gg-circle" => "gg-circle",
			"git" => "git",
			"git-square" => "git-square",
			"github" => "github",
			"github-alt" => "github-alt",
			"github-square" => "github-square",
			"google" => "google",
			"google-plus" => "google-plus",
			"google-plus-square" => "google-plus-square",
			"google-wallet" => "google-wallet",
			"gratipay" => "gratipay",
			"hacker-news" => "hacker-news",
			"houzz" => "houzz",
			"html5" => "html5",
			"instagram" => "instagram",
			"internet-explorer" => "internet-explorer",
			"ioxhost" => "ioxhost",
			"joomla" => "joomla",
			"jsfiddle" => "jsfiddle",
			"lastfm" => "lastfm",
			"lastfm-square" => "lastfm-square",
			"leanpub" => "leanpub",
			"linkedin" => "linkedin",
			"linkedin-square" => "linkedin-square",
			"linux" => "linux",
			"maxcdn" => "maxcdn",
			"meanpath" => "meanpath",
			"medium" => "medium",
			"odnoklassniki" => "odnoklassniki",
			"odnoklassniki-square" => "odnoklassniki-square",
			"opencart" => "opencart",
			"openid" => "openid",
			"opera" => "opera",
			"optin-monster" => "optin-monster",
			"pagelines" => "pagelines",
			"paypal" => "paypal",
			"pied-piper" => "pied-piper",
			"pied-piper-alt" => "pied-piper-alt",
			"pinterest" => "pinterest",
			"pinterest-p" => "pinterest-p",
			"pinterest-square" => "pinterest-square",
			"qq" => "qq",
			"rebel" => "rebel",
			"reddit" => "reddit",
			"reddit-square" => "reddit-square",
			"renren" => "renren",
			"safari" => "safari",
			"sellsy" => "sellsy",
			"share-alt" => "share-alt",
			"share-alt-square" => "share-alt-square",
			"shirtsinbulk" => "shirtsinbulk",
			"simplybuilt" => "simplybuilt",
			"skyatlas" => "skyatlas",
			"skype" => "skype",
			"slack" => "slack",
			"slideshare" => "slideshare",
			"soundcloud" => "soundcloud",
			"spotify" => "spotify",
			"stack-exchange" => "stack-exchange",
			"stack-overflow" => "stack-overflow",
			"steam" => "steam",
			"steam-square" => "steam-square",
			"stumbleupon" => "stumbleupon",
			"stumbleupon-circle" => "stumbleupon-circle",
			"tencent-weibo" => "tencent-weibo",
			"trello" => "trello",
			"tripadvisor" => "tripadvisor",
			"tumblr" => "tumblr",
			"tumblr-square" => "tumblr-square",
			"twitch" => "twitch",
			"twitter" => "twitter",
			"twitter-square" => "twitter-square",
			"viacoin" => "viacoin",
			"vimeo" => "vimeo",
			"vimeo-square" => "vimeo-square",
			"vine" => "vine",
			"vk" => "vk",
			"weibo" => "weibo",
			"weixin" => "weixin",
			"whatsapp" => "whatsapp",
			"wikipedia-w" => "wikipedia-w",
			"windows" => "windows",
			"wordpress" => "wordpress",
			"xing" => "xing",
			"xing-square" => "xing-square",
			"y-combinator" => "y-combinator",
			"yahoo" => "yahoo",
			"yelp" => "yelp",
			"youtube" => "youtube",
			"youtube-play" => "youtube-play"
		);
	}
}